CREATE TABLE finalizador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX finalizador_nome ON finalizador (nome);

CREATE TABLE caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    nome VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX caixa_filial_nome ON caixa (id_filial, nome);

CREATE TABLE usuario_caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario (id),
    id_caixa BIGINT NOT NULL REFERENCES caixa (id),
    padrao BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX usuario_caixa_usuario_caixa ON usuario_caixa (id_usuario, id_caixa);
CREATE INDEX usuario_caixa_caixa ON usuario_caixa (id_caixa);

CREATE TABLE caixa_sessao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caixa BIGINT NOT NULL REFERENCES caixa (id),
    id_usuario_abertura BIGINT NOT NULL REFERENCES usuario (id),
    id_usuario_fechamento BIGINT REFERENCES usuario (id),
    data VARCHAR(10) NOT NULL,
    aberto_em BIGINT NOT NULL,
    fechado_em BIGINT,
    observacao_abertura VARCHAR(500),
    observacao_fechamento VARCHAR(500),
    status VARCHAR(20) NOT NULL
);

CREATE INDEX caixa_sessao_caixa ON caixa_sessao (id_caixa);
CREATE INDEX caixa_sessao_status ON caixa_sessao (status);

CREATE TABLE venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    id_cliente BIGINT NOT NULL REFERENCES cliente (id),
    id_vendedor BIGINT NOT NULL REFERENCES usuario (id),
    id_caixa_sessao BIGINT NOT NULL REFERENCES caixa_sessao (id),
    id_cotacao BIGINT NOT NULL REFERENCES cotacao (id),
    total_pyg DOUBLE PRECISION NOT NULL,
    observacao VARCHAR(500),
    criado_em BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'finalizada'
);

CREATE INDEX venda_filial ON venda (id_filial);
CREATE INDEX venda_sessao ON venda (id_caixa_sessao);

CREATE TABLE venda_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda BIGINT NOT NULL REFERENCES venda (id),
    id_produto BIGINT NOT NULL REFERENCES produto (id),
    id_estoque BIGINT NOT NULL REFERENCES estoque (id),
    quantidade INTEGER NOT NULL,
    aliquota_iva INTEGER NOT NULL,
    moeda_preco VARCHAR(3) NOT NULL,
    preco_lista DOUBLE PRECISION NOT NULL,
    preco_unitario_pyg DOUBLE PRECISION NOT NULL,
    total_pyg DOUBLE PRECISION NOT NULL
);

CREATE INDEX venda_item_venda ON venda_item (id_venda);

CREATE TABLE venda_negociacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda BIGINT NOT NULL REFERENCES venda (id),
    id_finalizador BIGINT NOT NULL REFERENCES finalizador (id),
    valor DOUBLE PRECISION NOT NULL
);

CREATE INDEX venda_negociacao_venda ON venda_negociacao (id_venda);

CREATE TABLE caixa_movimentacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caixa_sessao BIGINT NOT NULL REFERENCES caixa_sessao (id),
    tipo VARCHAR(30) NOT NULL,
    id_usuario BIGINT NOT NULL REFERENCES usuario (id),
    id_venda BIGINT REFERENCES venda (id),
    id_movimentacao_par BIGINT,
    criado_em BIGINT NOT NULL,
    observacao VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE INDEX caixa_movimentacao_sessao ON caixa_movimentacao (id_caixa_sessao);

CREATE TABLE caixa_movimentacao_finalizador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caixa_movimentacao BIGINT NOT NULL REFERENCES caixa_movimentacao (id),
    id_finalizador BIGINT NOT NULL REFERENCES finalizador (id),
    valor DOUBLE PRECISION NOT NULL
);

CREATE INDEX caixa_mov_fin_mov ON caixa_movimentacao_finalizador (id_caixa_movimentacao);

INSERT INTO finalizador (nome, tipo, status) VALUES
    ('Dinheiro', 'dinheiro', 'ativo'),
    ('Cartão', 'cartao', 'ativo'),
    ('Depósito', 'deposito', 'ativo');

INSERT INTO caixa (id_filial, nome, status)
SELECT f.id, 'Caixa 1', 'ativo'
FROM filial f
WHERE f.status <> 'deletado';

INSERT INTO usuario_caixa (id_usuario, id_caixa, padrao, status)
SELECT u.id, c.id, CASE WHEN f.principal THEN TRUE ELSE FALSE END, 'ativo'
FROM usuario u
JOIN usuario_filial uf ON uf.id_usuario = u.id AND uf.status <> 'deletado'
JOIN caixa c ON c.id_filial = uf.id_filial AND c.status <> 'deletado'
JOIN filial f ON f.id = c.id_filial
WHERE u.status <> 'deletado';
