CREATE TABLE pessoa_endereco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa BIGINT NOT NULL REFERENCES pessoa (id),
    tipo VARCHAR(20) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    tipo_logradouro VARCHAR(30),
    logradouro VARCHAR(180),
    numero VARCHAR(20),
    bairro VARCHAR(80),
    cep VARCHAR(15),
    complemento VARCHAR(80),
    id_cidade BIGINT REFERENCES cidade (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo',
    id_pessoa_principal BIGINT
);

CREATE INDEX pessoa_endereco_pessoa ON pessoa_endereco (id_pessoa);
CREATE UNIQUE INDEX pessoa_endereco_principal_ativo ON pessoa_endereco (id_pessoa_principal);

INSERT INTO pessoa_endereco (
    id_pessoa, tipo, principal, tipo_logradouro, logradouro, numero, bairro, cep, complemento, id_cidade, status, id_pessoa_principal
)
SELECT
    id,
    'fiscal',
    TRUE,
    tipo_logradouro,
    logradouro,
    numero,
    bairro,
    cep,
    complemento,
    id_cidade,
    'ativo',
    id
FROM pessoa
WHERE coalesce(tipo_logradouro, '') <> ''
   OR coalesce(logradouro, '') <> ''
   OR coalesce(numero, '') <> ''
   OR coalesce(bairro, '') <> ''
   OR coalesce(cep, '') <> ''
   OR coalesce(complemento, '') <> ''
   OR id_cidade IS NOT NULL;

ALTER TABLE pessoa DROP COLUMN tipo_logradouro;
ALTER TABLE pessoa DROP COLUMN logradouro;
ALTER TABLE pessoa DROP COLUMN numero;
ALTER TABLE pessoa DROP COLUMN bairro;
ALTER TABLE pessoa DROP COLUMN cep;
ALTER TABLE pessoa DROP COLUMN complemento;
ALTER TABLE pessoa DROP COLUMN id_cidade;
