CREATE TABLE pais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(2) NOT NULL,
    usa_sigla_divisao BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX pais_sigla ON pais (sigla);

CREATE TABLE divisao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pais BIGINT NOT NULL REFERENCES pais (id),
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(10),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX divisao_id_pais_nome ON divisao (id_pais, nome);

CREATE TABLE cidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_divisao BIGINT NOT NULL REFERENCES divisao (id),
    nome VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX cidade_id_divisao_nome ON cidade (id_divisao, nome);

CREATE TABLE documento_tipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pais BIGINT NOT NULL REFERENCES pais (id),
    tipo_pessoa VARCHAR(20) NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    nome VARCHAR(80) NOT NULL,
    unico BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX documento_tipo_id_pais_codigo ON documento_tipo (id_pais, codigo);

CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_razao_social VARCHAR(180) NOT NULL,
    tipo_pessoa VARCHAR(20) NOT NULL,
    ddi VARCHAR(5),
    telefone VARCHAR(30),
    email VARCHAR(120),
    tipo_logradouro VARCHAR(30),
    logradouro VARCHAR(180),
    numero VARCHAR(20),
    bairro VARCHAR(80),
    cep VARCHAR(15),
    complemento VARCHAR(80),
    id_cidade BIGINT REFERENCES cidade (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE TABLE pessoa_documento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa BIGINT NOT NULL REFERENCES pessoa (id),
    id_pais BIGINT NOT NULL REFERENCES pais (id),
    id_tipo_documento BIGINT REFERENCES documento_tipo (id),
    tipo_livre VARCHAR(80),
    numero VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa BIGINT NOT NULL REFERENCES pessoa (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX cliente_id_pessoa ON cliente (id_pessoa);

CREATE TABLE fornecedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa BIGINT NOT NULL REFERENCES pessoa (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX fornecedor_id_pessoa ON fornecedor (id_pessoa);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(180) NOT NULL,
    email VARCHAR(120) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX usuario_email ON usuario (email);
