CREATE TABLE produto_unidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto BIGINT NOT NULL REFERENCES produto (id),
    id_estoque BIGINT NOT NULL REFERENCES estoque (id),
    numero VARCHAR(40) NOT NULL,
    situacao VARCHAR(20) NOT NULL DEFAULT 'disponivel',
    id_venda_item BIGINT REFERENCES venda_item (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX produto_unidade_numero ON produto_unidade (numero);
CREATE INDEX produto_unidade_produto ON produto_unidade (id_produto);
CREATE INDEX produto_unidade_estoque ON produto_unidade (id_estoque);

INSERT INTO produto_unidade (id_produto, id_estoque, numero, situacao, status)
SELECT pm.id_produto, f.id_estoque_padrao, UPPER(TRIM(pm.chassi)), 'disponivel', 'ativo'
FROM produto_moto pm
INNER JOIN produto p ON p.id = pm.id_produto
INNER JOIN filial f ON f.id = p.id_filial_cadastro
WHERE pm.chassi IS NOT NULL
  AND TRIM(pm.chassi) <> ''
  AND f.id_estoque_padrao IS NOT NULL
  AND p.status <> 'deletado';

UPDATE estoque_produto ep
SET quantidade = (
    SELECT COUNT(*)
    FROM produto_unidade u
    WHERE u.id_produto = ep.id_produto
      AND u.id_estoque = ep.id_estoque
      AND u.situacao = 'disponivel'
      AND u.status <> 'deletado'
)
WHERE EXISTS (
    SELECT 1 FROM produto_unidade u
    WHERE u.id_produto = ep.id_produto AND u.id_estoque = ep.id_estoque
);

ALTER TABLE produto_moto DROP COLUMN chassi;

CREATE TABLE venda_item_unidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda_item BIGINT NOT NULL REFERENCES venda_item (id),
    id_produto_unidade BIGINT NOT NULL REFERENCES produto_unidade (id)
);

CREATE UNIQUE INDEX venda_item_unidade_unidade ON venda_item_unidade (id_produto_unidade);
