ALTER TABLE finalizador ADD COLUMN gera_contas_receber BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE finalizador ADD COLUMN gera_contas_pagar BOOLEAN NOT NULL DEFAULT FALSE;

INSERT INTO finalizador (nome, tipo, status, gera_contas_receber, gera_contas_pagar)
SELECT 'Crediario', 'outro', 'ativo', TRUE, FALSE
WHERE NOT EXISTS (SELECT 1 FROM finalizador WHERE LOWER(nome) IN ('crediario', 'crediário'));

CREATE TABLE titulo_receber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    id_cliente BIGINT NOT NULL REFERENCES cliente (id),
    origem VARCHAR(20) NOT NULL,
    id_venda BIGINT REFERENCES venda (id),
    moeda VARCHAR(3) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL,
    id_cotacao BIGINT NOT NULL REFERENCES cotacao (id),
    usd_pyg DOUBLE PRECISION NOT NULL,
    brl_pyg DOUBLE PRECISION NOT NULL,
    observacao VARCHAR(500),
    criado_em BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberto'
);

CREATE INDEX titulo_receber_filial ON titulo_receber (id_filial);
CREATE INDEX titulo_receber_cliente ON titulo_receber (id_cliente);
CREATE INDEX titulo_receber_venda ON titulo_receber (id_venda);

CREATE TABLE parcela_receber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_titulo BIGINT NOT NULL REFERENCES titulo_receber (id),
    numero INTEGER NOT NULL,
    vencimento VARCHAR(10) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL,
    saldo DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberta'
);

CREATE UNIQUE INDEX parcela_receber_titulo_numero ON parcela_receber (id_titulo, numero);
CREATE INDEX parcela_receber_vencimento ON parcela_receber (vencimento);

CREATE TABLE baixa_receber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_parcela BIGINT NOT NULL REFERENCES parcela_receber (id),
    id_finalizador BIGINT NOT NULL REFERENCES finalizador (id),
    id_caixa_sessao BIGINT NOT NULL REFERENCES caixa_sessao (id),
    moeda VARCHAR(3) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL,
    id_usuario BIGINT NOT NULL REFERENCES usuario (id),
    criado_em BIGINT NOT NULL,
    observacao VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE INDEX baixa_receber_parcela ON baixa_receber (id_parcela);

CREATE TABLE titulo_pagar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    id_fornecedor BIGINT NOT NULL REFERENCES fornecedor (id),
    origem VARCHAR(20) NOT NULL,
    moeda VARCHAR(3) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL,
    id_cotacao BIGINT NOT NULL REFERENCES cotacao (id),
    usd_pyg DOUBLE PRECISION NOT NULL,
    brl_pyg DOUBLE PRECISION NOT NULL,
    observacao VARCHAR(500),
    criado_em BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberto'
);

CREATE INDEX titulo_pagar_filial ON titulo_pagar (id_filial);
CREATE INDEX titulo_pagar_fornecedor ON titulo_pagar (id_fornecedor);

CREATE TABLE parcela_pagar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_titulo BIGINT NOT NULL REFERENCES titulo_pagar (id),
    numero INTEGER NOT NULL,
    vencimento VARCHAR(10) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL,
    saldo DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberta'
);

CREATE UNIQUE INDEX parcela_pagar_titulo_numero ON parcela_pagar (id_titulo, numero);
CREATE INDEX parcela_pagar_vencimento ON parcela_pagar (vencimento);

CREATE TABLE baixa_pagar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_parcela BIGINT NOT NULL REFERENCES parcela_pagar (id),
    id_finalizador BIGINT NOT NULL REFERENCES finalizador (id),
    id_caixa_sessao BIGINT NOT NULL REFERENCES caixa_sessao (id),
    moeda VARCHAR(3) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL,
    id_usuario BIGINT NOT NULL REFERENCES usuario (id),
    criado_em BIGINT NOT NULL,
    observacao VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE INDEX baixa_pagar_parcela ON baixa_pagar (id_parcela);

ALTER TABLE caixa_movimentacao ADD COLUMN id_baixa_receber BIGINT;
ALTER TABLE caixa_movimentacao ADD COLUMN id_baixa_pagar BIGINT;
