CREATE TABLE entrada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    id_fornecedor BIGINT NOT NULL REFERENCES fornecedor (id),
    tipo_documento VARCHAR(20) NOT NULL,
    data_emissao VARCHAR(10) NOT NULL,
    moeda VARCHAR(3) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL,
    id_cotacao BIGINT NOT NULL REFERENCES cotacao (id),
    usd_pyg DOUBLE PRECISION NOT NULL,
    brl_pyg DOUBLE PRECISION NOT NULL,
    timbrado VARCHAR(20),
    establecimiento VARCHAR(10),
    punto_expedicion VARCHAR(10),
    numero VARCHAR(20),
    cdc VARCHAR(44),
    condicion VARCHAR(20),
    numero_documento VARCHAR(60),
    incoterm VARCHAR(20),
    id_caixa_sessao BIGINT REFERENCES caixa_sessao (id),
    observacao VARCHAR(500),
    criado_em BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'finalizada'
);

CREATE INDEX entrada_filial ON entrada (id_filial);
CREATE INDEX entrada_fornecedor ON entrada (id_fornecedor);
CREATE INDEX entrada_data ON entrada (data_emissao);
CREATE INDEX entrada_py_doc ON entrada (id_filial, id_fornecedor, timbrado, establecimiento, punto_expedicion, numero);
CREATE TABLE entrada_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entrada BIGINT NOT NULL REFERENCES entrada (id),
    id_produto BIGINT NOT NULL REFERENCES produto (id),
    id_estoque BIGINT NOT NULL REFERENCES estoque (id),
    quantidade INTEGER NOT NULL,
    aliquota_iva INTEGER NOT NULL,
    moeda VARCHAR(3) NOT NULL,
    valor_unitario DOUBLE PRECISION NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL
);

CREATE INDEX entrada_item_entrada ON entrada_item (id_entrada);

CREATE TABLE entrada_item_unidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entrada_item BIGINT NOT NULL REFERENCES entrada_item (id),
    id_produto_unidade BIGINT NOT NULL REFERENCES produto_unidade (id)
);

CREATE UNIQUE INDEX entrada_item_unidade_unica ON entrada_item_unidade (id_produto_unidade);
CREATE INDEX entrada_item_unidade_item ON entrada_item_unidade (id_entrada_item);

CREATE TABLE entrada_negociacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entrada BIGINT NOT NULL REFERENCES entrada (id),
    id_finalizador BIGINT NOT NULL REFERENCES finalizador (id),
    moeda VARCHAR(3) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    valor_pyg DOUBLE PRECISION NOT NULL
);

CREATE INDEX entrada_negociacao_entrada ON entrada_negociacao (id_entrada);

ALTER TABLE titulo_pagar ADD COLUMN id_entrada BIGINT REFERENCES entrada (id);
CREATE INDEX titulo_pagar_entrada ON titulo_pagar (id_entrada);

ALTER TABLE caixa_movimentacao ADD COLUMN id_entrada BIGINT;

INSERT INTO finalizador (nome, tipo, status, gera_contas_receber, gera_contas_pagar)
SELECT 'Prazo fornecedor', 'outro', 'ativo', FALSE, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM finalizador WHERE LOWER(nome) = 'prazo fornecedor'
);
