CREATE TABLE factura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    id_venda BIGINT NOT NULL REFERENCES venda (id),
    referencia VARCHAR(80) NOT NULL,
    sudtax_id BIGINT,
    cdc VARCHAR(44),
    cdc_formatado VARCHAR(80),
    estado VARCHAR(20) NOT NULL DEFAULT 'pendente',
    mensagem VARCHAR(500),
    protocolo_lote VARCHAR(80),
    codigo_sifen VARCHAR(40),
    estabelecimento VARCHAR(10),
    ponto_expedicao VARCHAR(10),
    cliente_nome VARCHAR(200) NOT NULL,
    total_pyg DOUBLE PRECISION NOT NULL,
    payload_envio TEXT,
    criado_em BIGINT NOT NULL,
    atualizado_em BIGINT NOT NULL
);

CREATE UNIQUE INDEX factura_venda_unica ON factura (id_venda);
CREATE UNIQUE INDEX factura_referencia_unica ON factura (referencia);
CREATE INDEX factura_filial ON factura (id_filial);
CREATE INDEX factura_sudtax ON factura (sudtax_id);
CREATE INDEX factura_estado ON factura (estado);
CREATE INDEX factura_criado ON factura (criado_em);
