ALTER TABLE baixa_receber ADD COLUMN desconto DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE baixa_receber ADD COLUMN desconto_pyg DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE baixa_receber ADD COLUMN acrescimo DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE baixa_receber ADD COLUMN acrescimo_pyg DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE baixa_pagar ADD COLUMN desconto DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE baixa_pagar ADD COLUMN desconto_pyg DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE baixa_pagar ADD COLUMN acrescimo DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE baixa_pagar ADD COLUMN acrescimo_pyg DOUBLE PRECISION NOT NULL DEFAULT 0;
