CREATE TABLE empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(180) NOT NULL,
    nome_fantasia VARCHAR(120) NOT NULL,
    ruc VARCHAR(15) NOT NULL,
    representante_nome VARCHAR(120),
    representante_documento VARCHAR(40),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX empresa_ruc ON empresa (ruc);

CREATE TABLE filial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa BIGINT NOT NULL REFERENCES empresa (id),
    nome VARCHAR(120) NOT NULL,
    ddi VARCHAR(5),
    telefone VARCHAR(30),
    email VARCHAR(120),
    tipo_logradouro VARCHAR(30),
    logradouro VARCHAR(180),
    numero VARCHAR(20),
    bairro VARCHAR(80),
    cep VARCHAR(15),
    complemento VARCHAR(80),
    id_cidade BIGINT REFERENCES cidade (id),
    timbrado VARCHAR(20),
    timbrado_vigencia_inicio VARCHAR(10),
    timbrado_vigencia_fim VARCHAR(10),
    estabelecimento_numero VARCHAR(10),
    ponto_expedicao VARCHAR(10),
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE INDEX filial_id_empresa ON filial (id_empresa);

ALTER TABLE cliente ADD COLUMN id_filial_cadastro BIGINT REFERENCES filial (id);
ALTER TABLE fornecedor ADD COLUMN id_filial_cadastro BIGINT REFERENCES filial (id);

-- Seed inicial: empresa + filial matriz (RUC válido para edição posterior)
INSERT INTO empresa (razao_social, nome_fantasia, ruc, status)
VALUES ('Monarca Bike S.R.L.', 'Monarca Bike', '80009735-1', 'ativo');

INSERT INTO filial (id_empresa, nome, principal, status)
VALUES (1, 'Matriz', TRUE, 'ativo');

UPDATE cliente SET id_filial_cadastro = 1 WHERE id_filial_cadastro IS NULL;
UPDATE fornecedor SET id_filial_cadastro = 1 WHERE id_filial_cadastro IS NULL;
