ALTER TABLE filial ADD COLUMN listar_apenas_clientes_filial BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE filial ADD COLUMN listar_apenas_fornecedores_filial BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE cliente_filial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES cliente (id),
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX cliente_filial_cliente_filial ON cliente_filial (id_cliente, id_filial);

CREATE TABLE fornecedor_filial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_fornecedor BIGINT NOT NULL REFERENCES fornecedor (id),
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX fornecedor_filial_fornecedor_filial ON fornecedor_filial (id_fornecedor, id_filial);

INSERT INTO cliente_filial (id_cliente, id_filial, status)
SELECT c.id, c.id_filial_cadastro, c.status
FROM cliente c
WHERE c.id_filial_cadastro IS NOT NULL
  AND c.status <> 'deletado';

INSERT INTO fornecedor_filial (id_fornecedor, id_filial, status)
SELECT f.id, f.id_filial_cadastro, f.status
FROM fornecedor f
WHERE f.id_filial_cadastro IS NOT NULL
  AND f.status <> 'deletado';
