CREATE TABLE usuario_filial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario (id),
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX usuario_filial_usuario_filial ON usuario_filial (id_usuario, id_filial);
CREATE INDEX usuario_filial_filial ON usuario_filial (id_filial);

INSERT INTO usuario_filial (id_usuario, id_filial, status)
SELECT u.id, f.id, 'ativo'
FROM usuario u
CROSS JOIN filial f
WHERE u.status <> 'deletado'
  AND f.status <> 'deletado';
