CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL,
    nome VARCHAR(180) NOT NULL,
    marca VARCHAR(80) NOT NULL,
    descricao VARCHAR(500),
    tipo VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE TABLE produto_moto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto BIGINT NOT NULL REFERENCES produto (id),
    potencia_motor_w INTEGER,
    autonomia_km INTEGER,
    velocidade_max_kmh INTEGER,
    capacidade_bateria_ah DOUBLE PRECISION,
    voltagem_bateria INTEGER,
    tempo_carga_horas DOUBLE PRECISION,
    peso_kg DOUBLE PRECISION,
    capacidade_carga_kg INTEGER,
    assentos INTEGER,
    tipo_freio VARCHAR(60),
    CONSTRAINT produto_moto_id_produto UNIQUE (id_produto)
);

CREATE TABLE produto_bicicleta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto BIGINT NOT NULL REFERENCES produto (id),
    potencia_motor_w INTEGER,
    autonomia_km INTEGER,
    capacidade_bateria_ah DOUBLE PRECISION,
    voltagem_bateria INTEGER,
    tempo_carga_horas DOUBLE PRECISION,
    peso_kg DOUBLE PRECISION,
    aro VARCHAR(20),
    tipo_quadro VARCHAR(40),
    numero_marchas INTEGER,
    tipo_freio VARCHAR(60),
    CONSTRAINT produto_bicicleta_id_produto UNIQUE (id_produto)
);

CREATE TABLE estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    nome VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE TABLE estoque_produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estoque BIGINT NOT NULL REFERENCES estoque (id),
    id_produto BIGINT NOT NULL REFERENCES produto (id),
    quantidade INTEGER NOT NULL DEFAULT 0,
    quantidade_reservada INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo',
    CONSTRAINT estoque_produto_estoque_produto UNIQUE (id_estoque, id_produto)
);

INSERT INTO estoque (id_filial, nome, status)
SELECT id, 'Estoque Geral', 'ativo'
FROM filial
WHERE status <> 'deletado';
