ALTER TABLE filial ADD COLUMN listar_apenas_produtos_filial BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE produto ADD COLUMN id_filial_cadastro BIGINT REFERENCES filial (id);

ALTER TABLE produto_moto ADD COLUMN chassi VARCHAR(40);
ALTER TABLE produto_moto ADD COLUMN cor VARCHAR(40);

ALTER TABLE produto_bicicleta ADD COLUMN cor VARCHAR(40);

CREATE TABLE produto_filial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto BIGINT NOT NULL REFERENCES produto (id),
    id_filial BIGINT NOT NULL REFERENCES filial (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

CREATE UNIQUE INDEX produto_filial_produto_filial ON produto_filial (id_produto, id_filial);

INSERT INTO produto_filial (id_produto, id_filial, status)
SELECT p.id, p.id_filial_cadastro, p.status
FROM produto p
WHERE p.id_filial_cadastro IS NOT NULL
  AND p.status <> 'deletado';
