CREATE TABLE marca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

INSERT INTO marca (nome, status) VALUES ('Monarca', 'ativo');

CREATE TABLE modelo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_marca BIGINT NOT NULL REFERENCES marca (id),
    nome VARCHAR(120) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);

ALTER TABLE produto ADD COLUMN id_marca BIGINT REFERENCES marca (id);
ALTER TABLE produto ADD COLUMN id_modelo BIGINT REFERENCES modelo (id);

INSERT INTO marca (nome, status)
SELECT DISTINCT TRIM(p.marca), 'ativo'
FROM produto p
WHERE p.marca IS NOT NULL AND TRIM(p.marca) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM marca m
      WHERE LOWER(m.nome) = LOWER(TRIM(p.marca))
  );

INSERT INTO modelo (id_marca, nome, tipo, status)
SELECT DISTINCT m.id,
       CASE WHEN LENGTH(TRIM(p.nome)) > 0 THEN TRIM(p.nome) ELSE 'Padrão' END,
       p.tipo,
       'ativo'
FROM produto p
JOIN marca m ON LOWER(m.nome) = LOWER(TRIM(p.marca))
WHERE p.id_modelo IS NULL
  AND p.marca IS NOT NULL
  AND TRIM(p.marca) <> '';

INSERT INTO modelo (id_marca, nome, tipo, status)
SELECT DISTINCT (SELECT id FROM marca WHERE LOWER(nome) = 'monarca' LIMIT 1),
       CASE WHEN LENGTH(TRIM(p.nome)) > 0 THEN TRIM(p.nome) ELSE 'Padrão' END,
       p.tipo,
       'ativo'
FROM produto p
WHERE p.id_modelo IS NULL
  AND (p.marca IS NULL OR TRIM(p.marca) = '');

UPDATE produto
SET id_marca = (
    SELECT m.id FROM marca m
    WHERE LOWER(m.nome) = LOWER(TRIM(produto.marca))
    LIMIT 1
)
WHERE id_marca IS NULL
  AND marca IS NOT NULL
  AND TRIM(marca) <> '';

UPDATE produto
SET id_marca = (SELECT id FROM marca WHERE LOWER(nome) = 'monarca' LIMIT 1)
WHERE id_marca IS NULL;

UPDATE produto
SET id_modelo = (
    SELECT mo.id FROM modelo mo
    WHERE mo.id_marca = produto.id_marca
      AND mo.tipo = produto.tipo
      AND LOWER(mo.nome) = LOWER(TRIM(produto.nome))
    LIMIT 1
)
WHERE id_modelo IS NULL;

UPDATE produto
SET id_modelo = (
    SELECT mo.id FROM modelo mo
    WHERE mo.id_marca = produto.id_marca AND mo.tipo = produto.tipo
    ORDER BY mo.id
    LIMIT 1
)
WHERE id_modelo IS NULL;

ALTER TABLE produto ALTER COLUMN id_marca SET NOT NULL;
ALTER TABLE produto ALTER COLUMN id_modelo SET NOT NULL;

UPDATE produto
SET nome = (
    SELECT m.nome || ' ' || mo.nome
    FROM marca m
    JOIN modelo mo ON mo.id = produto.id_modelo
    WHERE m.id = produto.id_marca
);

ALTER TABLE produto DROP COLUMN marca;

ALTER TABLE produto_moto ADD COLUMN ano_fabricacao INTEGER;
ALTER TABLE produto_moto ADD COLUMN ano_modelo INTEGER;

UPDATE produto_moto
SET ano_fabricacao = CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS INTEGER),
    ano_modelo = CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS INTEGER)
WHERE ano_fabricacao IS NULL;

ALTER TABLE produto_moto ALTER COLUMN ano_fabricacao SET NOT NULL;
ALTER TABLE produto_moto ALTER COLUMN ano_modelo SET NOT NULL;

ALTER TABLE produto_bicicleta ADD COLUMN numero_serie_quadro VARCHAR(40);
