package com.monarca.localidade.repository

internal data class DivisaoSeed(val nome: String, val sigla: String? = null)

internal val ufsBrasil = listOf(
    DivisaoSeed("Acre", "AC"),
    DivisaoSeed("Alagoas", "AL"),
    DivisaoSeed("Amapá", "AP"),
    DivisaoSeed("Amazonas", "AM"),
    DivisaoSeed("Bahia", "BA"),
    DivisaoSeed("Ceará", "CE"),
    DivisaoSeed("Distrito Federal", "DF"),
    DivisaoSeed("Espírito Santo", "ES"),
    DivisaoSeed("Goiás", "GO"),
    DivisaoSeed("Maranhão", "MA"),
    DivisaoSeed("Mato Grosso", "MT"),
    DivisaoSeed("Mato Grosso do Sul", "MS"),
    DivisaoSeed("Minas Gerais", "MG"),
    DivisaoSeed("Pará", "PA"),
    DivisaoSeed("Paraíba", "PB"),
    DivisaoSeed("Paraná", "PR"),
    DivisaoSeed("Pernambuco", "PE"),
    DivisaoSeed("Piauí", "PI"),
    DivisaoSeed("Rio de Janeiro", "RJ"),
    DivisaoSeed("Rio Grande do Norte", "RN"),
    DivisaoSeed("Rio Grande do Sul", "RS"),
    DivisaoSeed("Rondônia", "RO"),
    DivisaoSeed("Roraima", "RR"),
    DivisaoSeed("Santa Catarina", "SC"),
    DivisaoSeed("São Paulo", "SP"),
    DivisaoSeed("Sergipe", "SE"),
    DivisaoSeed("Tocantins", "TO"),
)

internal val departamentosParaguai = listOf(
    DivisaoSeed("Concepción"),
    DivisaoSeed("San Pedro"),
    DivisaoSeed("Cordillera"),
    DivisaoSeed("Guairá"),
    DivisaoSeed("Caaguazú"),
    DivisaoSeed("Caazapá"),
    DivisaoSeed("Itapúa"),
    DivisaoSeed("Misiones"),
    DivisaoSeed("Paraguarí"),
    DivisaoSeed("Alto Paraná"),
    DivisaoSeed("Central"),
    DivisaoSeed("Ñeembucú"),
    DivisaoSeed("Amambay"),
    DivisaoSeed("Canindeyú"),
    DivisaoSeed("Presidente Hayes"),
    DivisaoSeed("Alto Paraguay"),
    DivisaoSeed("Boquerón"),
    DivisaoSeed("Asunción"),
)
